export { default as Appoitment } from "./Appoitment";
export { default as SectionTitle } from "./SectionTitle";
export { default as GrayText } from "./GrayText";
export { default as Button } from "./Button";
export { default as Badge } from "./Badge";
export { default as PlusButton } from "./PlusButton";
export { default as CustomInput } from "./CustomInput";
export { default as CustomSwitch } from "./CustomSwitch";
export { default as Tooth } from "./Tooth";
